---
  # This task will get necessary information about Apache installed
  - name: Get Apache Info
    hosts: localhost #Change Host Inventory
    tasks:

    # Reterive Apache Version
    - name: Get Apache Version
      shell: "hostname && httpd -v"
      register: httpd_ver

    - debug: var=httpd_ver.stdout_lines

    # Reterive installed Apache Packages
    - name: Get Apache Packages
      shell: "rpm -qa | grep http"
      register: httpd_pack

    - debug: var=httpd_pack.stdout_lines

    # Reterive Apache Modules
    - name: Get Apache Modules
      shell: "httpd -M"
      register: httpd_mods

    - debug: var=httpd_mods.stdout_lines