---

    - name: Run PowerShell Command
      ansible.builtin.win_shell: Get-HotFix | where {$_.InstalledOn -gt "09/01/2022" -AND $_.InstalledOn -lt "09/30/2022" } | sort InstalledOn
      args:
        executable: powershell.exe 
      register: pwsh_out
      
    - debug: var:pwsh_out.stdout_lines 