---

  - name: Start Hashing
    hosts: lin
    tasks:

    - name: Convert hash.txt to Unix format
      become: yes
      shell: "dos2unix -n hash.txt hashlinux.txt"
      args:
        chdir: "/opt/hash"
      delegate_to: 127.0.0.1
      register: convert_info   

    - name: Get hash value of hash.txt on Ansible Tower
      stat:
        path: /opt/hash/hashlinux.txt
        checksum_algorithm: sha1
      delegate_to: 127.0.0.1
      register: source_info

    - debug: var=source_info.stat.checksum

    - name: Copy hashlinux.txt to slave
      copy:
        src: /opt/hash/hashlinux.txt
        dest: /opt/hash/hashlinux.txt
        force: yes
      register: copy_out

    - name: Get hash value of hashlinux.txt on slave
      stat:
        path: /opt/hash/hashlinux.txt
        checksum_algorithm: sha1
      register: copy_info

    - name: Fail if copy was a failure
      fail:
        msg: "Copy failed"
      when: source_info.stat.checksum != copy_info.stat.checksum    

    - name: Print Copy successful
      debug:
        msg: "Copy Successul!"

    - name: Running hashing Script
      become: yes
      become_user: root
      shell: "./hashscan.sh"
      args:
        chdir: "/opt/hash"
      register: hashscan  

    - debug: var=hashscan.stdout_lines