---

  - name: Start Hashing
    hosts: linux #Change the host list
    tasks:

    # This task will create a Unix format file "hashlinux.txt" in /tmp/hash/
    # This task will be run on the Ansible Tower
    - name: 01 - Convert hash.txt to Unix format
      shell: "dos2unix -n hash.txt hashlinux.txt"
      args:
        chdir: "/tmp/hash"
      delegate_to: azanwspr01.pseraya.com.sg
      register: convert_info   

    # This task will get the SHA1 value of the hashlinux.txt
    # Task is ran on the Ansible Tower
    - name: 02 - Get hash value of hashlinux.txt on Ansible Tower
      stat:
        path: /tmp/hash/hashlinux.txt
        checksum_algorithm: md5
      delegate_to: azanwspr01.pseraya.com.sg
      register: source_info

    - debug: var=source_info.stat.checksum

    # This task will copy hashlinux.txt to the slave server.
    - name: 03 - Copy hashlinux.txt to slave
      become: yes
      copy:
        src: /tmp/hash/hashlinux.txt
        dest: /tmp/hash/hashlinux.txt
        force: yes
      register: copy_out

    # This task will get the SHA1 value of the hashlinux.txt on the slave server
    - name: 04 - Get hash value of hashlinux.txt on slave
      stat:
        path: /tmp/hash/hashlinux.txt
        checksum_algorithm: md5
      register: copy_info

    - debug: var=copy_info.stat.checksum

    # This task will compare the SHA1 values from tasks 02 & 04. And stop all future tasks if the SHA values mismatch
    - name: 05 - Fail if copy was a failure
      fail:
        msg: "Copy failed"
      when: source_info.stat.checksum != copy_info.stat.checksum    

    - name: 06 - Print Copy successful
      debug:
        msg: "Copy Successul!"

    # This task will run the hashing script
    - name: 07 - Running hashing Script
      become: yes
      become_user: root
      shell: "./SecurityHashScan.sh"
      args:
        chdir: "/opt/hash"
      register: hashscan  

    - debug: var=hashscan.stdout_lines