---
- name: Patch Red Hat Linux servers
  hosts: localhost
  become: yes

  tasks:
    - name: Update package cache
      yum:
        update_cache: yes

    - name: Install available updates
      yum:
        name: "*"
        state: latest

    - name: Reboot servers if updates require it
      reboot:
        msg: "Updates installed, rebooting now."
        connect_timeout: 10
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: ansible_reboot_pending | bool