---
- name: Set up WordPress server
  hosts: localhost
  become: yes

  vars:
    mysql_root_password: password  # Change this to the desired MySQL root password
    wordpress_db_name: wordpress  # Change this to the desired WordPress database name
    wordpress_db_user: wordpressuser  # Change this to the desired WordPress database username
    wordpress_db_password: password  # Change this to the desired WordPress database password

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Install PHP and required modules
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
          - php-gd
          - php-curl
        state: present

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Secure MySQL installation
      mysql_user:
        login_user: root
        login_password: ''
        name: root
        password: "{{ mysql_root_password }}"
        host_all: yes
        check_implicit_admin: yes
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create WordPress database
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ wordpress_db_name }}"
        encoding: utf8
        state: present

    - name: Create WordPress database user
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ wordpress_db_user }}"
        password: "{{ wordpress_db_password }}"
        priv: "{{ wordpress_db_name }}.*:ALL"
        state: present

    - name: Download and extract WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz
      register: wordpress_download

    - name: Extract WordPress archive
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set correct ownership and permissions for WordPress
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Set up WordPress configuration file
      template:
        src: templates/wp-config.php.j2
        dest: /var/www/html/wp-config.php
        owner: www-data
        group: www-data
        mode: '0640'

    - name: Restart Apache web server
      service:
        name: apache2
        state: restarted
