---
- name: Retrieve and install patches on Red Hat 8 server
  hosts: redhat_server
  become: true

  tasks:
    - name: Check for available updates
      redhat_subscription:
        state: list

    - name: Install available updates
      redhat_subscription:
        state: latest