---
  - name: Gather OpenSSl Information
    hosts: lin
    tasks:

    - name: Get OpenSSl Version
      become: yes
      shell: "openssl version -a"
      register: openssl_ver

    - debug: var=openssl_ver.stdout_lines

    - name: Get OpenSSl Packages
      become: yes
      shell: "rpm -qa | grep openssl"
      register: openssl_packages

    - debug: var=openssl_packages.stdout_lines