---
- name: Reset user password
  hosts: all
  become: true
  vars_prompt:
    - name: username
      prompt: "Enter username"
      private: false
  tasks:
    - name: Set new password
      shell: echo "{{ new_password }}" | passwd --stdin "{{ username }}"
      vars_prompt:
        - name: new_password
          prompt: "Enter new password"
          private: true