---
- name: Set up NGINX reverse proxy server
  hosts: proxy_server
  become: true

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Configure NGINX as reverse proxy
      copy:
        src: files/default.conf
        dest: /etc/nginx/conf.d/default.conf
        mode: 0644
      notify:
        - restart nginx

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
